### ISSUE TITLE
Real image editing

### ISSUE THREAD

**Issue by christianchartier** [CompVis/attribute-control#1]
This is great! Do you plant to implement support for real image editing?

**Comment by stefan-baumann** [comment]
Thanks for the suggestion! It should be straightforward to implement via methods like Null-Text-Inversion+ Prompt-to-Prompt, especially as I already have an implementation for P2P in my research codebase. Let me see if I can implement something quickly.

**Comment by stefan-baumann** [comment]
I implemented this based on ReNoise with SDXL Turbo as the backend to make things snappy. You can find a notebook here: https://github.com/CompVis/attribute-control/tree/main/notebooks/real_image_editing

**Comment by christianchartier** [comment]
This is great, thanks for taking the time to implement so quickly!
